[package]
name = "axum_auth_backend"
version = "0.1.0"
edition = "2024"

[dependencies]
argon2 = "0.5.3"
async-trait = "0.1.92"
axum = "0.8.9"
axum-extra = "0.12.6"
dotenv = "0.15.0"
jsonwebtoken = "11.0.0"
lettre = "0.11.23"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
sqlx = { version = "0.9.0", features = ["runtime-tokio", "tls-native-tls", "postgres", "chrono", "uuid"] }
chrono = { version = "0.4.45", features = ["serde"] }
time = "0.3.55"
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread"] }
tower = "0.5.3"
tower-http = { version = "0.7.0", features = ["cors", "trace"]}
tracing-subscriber = "0.3.23"
uuid = { version = "1.25.0", features = ["serde", "v4"] }
validator = { version = "0.21.0", features = ["derive"] }
